[variables]
NIXPACKS_PHP_VERSION = "7.4"

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
